[project]
name = "stremio-library-exporter"
version = "0.1.0"
description = "Stremio Library Extractor Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.54.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
